#pragma once

#include <config.h>
#include <jorum/arch/x86/asm/constants.h>
#include <jorum/arch/x86/asm/gdtl.h>

// GDT Making

#define GDT_MK_PRESENT(x) ((x) << 0x07)
#define GDT_MK_PRIV(x) (((x) & 0x03) << 0x05)
#define GDT_MK_LONG(x) ((x) << 0x01)
#define GDT_MK_WIDTH(x) ((x) << 0x02)
#define GDT_MK_GRAN(x) ((x) << 0x03)

#define GDT_RX 0x0A
#define GDT_RW 0x02

#define GDT_CODEDATA (1 << 0x04)
#define GDT_PRESENT GDT_MK_PRESENT(1)

#if CONFIG_ARCH64
#define GDT_LONG GDT_MK_LONG(1)
#define GDT_WIDTH GDT_MK_WIDTH(0)
#elif CONFIG_ARCH32
#define GDT_LONG GDT_MK_LONG(0)
#define GDT_WIDTH GDT_MK_WIDTH(1)
#else
#error "Unsupported architecture width"
#endif

#define GDT_GRANULARITY GDT_MK_GRAN(1)
#define GDT_PRIV_KERNEL GDT_MK_PRIV(KERNEL_RING)
#define GDT_PRIV_USER GDT_MK_PRIV(USER_RING)

#define GDT_CODE_FLAGS (GDT_LONG | GDT_WIDTH | GDT_GRANULARITY)
#define GDT_DATA_FLAGS (GDT_WIDTH | GDT_GRANULARITY)

#define GDT_CODE_ACCESS (GDT_PRESENT | GDT_CODEDATA | GDT_RX)
#define GDT_DATA_ACCESS (GDT_PRESENT | GDT_CODEDATA | GDT_RW)

#define GDT_KERNEL_CODE_ACCESS (GDT_CODE_ACCESS | GDT_PRIV_KERNEL)
#define GDT_KERNEL_DATA_ACCESS (GDT_DATA_ACCESS | GDT_PRIV_KERNEL)
#define GDT_USER_CODE_ACCESS (GDT_CODE_ACCESS | GDT_PRIV_USER)
#define GDT_USER_DATA_ACCESS (GDT_DATA_ACCESS | GDT_PRIV_USER)

#define GDT_BASE 0
#define GDT_LIMIT 0xFFFFF

#define GDT_NULL_SEGMENT GDT_ENTRY(GDT_BASE, 0, 0, 0)

#define GDT_KERNEL_CODE_SELECTOR GDT_SELECTOR(1, KERNEL_RING)
#define GDT_KERNEL_DATA_SELECTOR GDT_SELECTOR(2, KERNEL_RING)
#define GDT_USER_CODE_SELECTOR GDT_SELECTOR(3, USER_RING)
#define GDT_USER_DATA_SELECTOR GDT_SELECTOR(4, USER_RING)

#define GDT_KERNEL_CODE GDT_ENTRY(GDT_BASE, GDT_LIMIT, GDT_KERNEL_CODE_ACCESS, GDT_CODE_FLAGS)
#define GDT_KERNEL_DATA GDT_ENTRY(GDT_BASE, GDT_LIMIT, GDT_KERNEL_DATA_ACCESS, GDT_DATA_FLAGS)
#define GDT_USER_CODE GDT_ENTRY(GDT_BASE, GDT_LIMIT, GDT_USER_CODE_ACCESS, GDT_CODE_FLAGS)
#define GDT_USER_DATA GDT_ENTRY(GDT_BASE, GDT_LIMIT, GDT_USER_DATA_ACCESS, GDT_DATA_FLAGS)
